project_dir ="~/www/rust/test"
# maybe vim or other alias of you
editor="vim"
# the ycm_extra_conf.py if you use Youcompleteme
ycm_extra_conf = ".ycm_extra_conf.py"

# rust-project.json content
rust_project_json = """
{
    "sysroot_src":"~/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library",
    "crates":[
        {
            "root_module":"{#file_name}",
            "edition":"2021",
            "deps":[

            ]
        }
    ]
}
"""
# cargo.toml content
cargo_toml = """
[package]
name = "leetcode"
version = "0.1.0"
edition = "2021"

[lib]
path='./{#file_name}'

[dependencies]
"""
